export enum ApplicationStatus {
  AWAITING_RESPONSE = 'Awaiting response',
  HR_REACHED_BACK = 'HR reached me back',
  AWAITING_DECISION = 'Awaiting decision',
  DECIDED_TO_PASS = 'Decided to pass',
  LOW_SALARY = 'Below expectations',
  DID_NOT_PASS_HR = "Didn't pass HR",
  AWAITING_INTERVIEW = 'Awaiting interview',
  INTERVIEW_SCHEDULED = 'Interview scheduled',
  AWAITING_RESULTS = 'Awaiting interview results',
  REJECTED = 'Rejected',
  PASSED = 'Passed',
  PROBABLY_NOT = "Probably didn't pass",
  REAPPLIED = 'Reapplied',
  ARCHIVED = 'Archived',
  RECEIVED_CONTRACT = 'Received a contract',
  CONTRACT_ACCEPTED = 'Accepted offer',
  CONTRACT_DECLINED = 'Declined offer',
}

export const TERMINAL_STATUSES: ReadonlySet<ApplicationStatus> = new Set([
  ApplicationStatus.DECIDED_TO_PASS,
  ApplicationStatus.LOW_SALARY,
  ApplicationStatus.DID_NOT_PASS_HR,
  ApplicationStatus.REJECTED,
  ApplicationStatus.PASSED,
  ApplicationStatus.PROBABLY_NOT,
  ApplicationStatus.ARCHIVED,
  ApplicationStatus.CONTRACT_ACCEPTED,
  ApplicationStatus.CONTRACT_DECLINED,
]);
